#!/usr/bin/bash

######################################## File Description ########################################
# Creation time：2020-05-31
# Project：08
# Task: 05
# Execute example：bash record-shell-x-x.sh
# Detailed description：
# About：http://linux.book.51xueweb.cn
##################################################################################################

#reback start
cd /etc/yum.repos.d
cp CentOS-Base.repo CentOS-Base.repo.bak
cp CentOS-AppStream.repo CentOS-AppStream.repo.bak
cp CentOS-Extras.repo CentOS-Extras.repo.bak

sed -i 's|mirrorlist=|#mirrorlist=|g' CentOS-Base.repo CentOS-AppStream.repo CentOS-Extras.repo
sed -i 's|#baseurl=|baseurl=|g' CentOS-Base.repo CentOS-AppStream.repo CentOS-Extras.repo
sed -i 's|http://mirror.centos.org|https://mirrors.aliyun.com|g' CentOS-Base.repo CentOS-AppStream.repo CentOS-Extras.repo

yum remove -y bind-utils

cp -f /etc/named.conf.bak1 /etc/named.conf
yum remove -y bind-utils
rm -f /var/named/com-domain-area
rm -f /var/named/10.10.3.area
rm -f /var/named/com-domain-common
rm -f /var/named/10.10.4.common
yum remove -y bind
yum clean all
echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear
#reback end

#***************reader shell start***************
echo "[root@Project-08-Task-05 ~]# nmcli"
sleep 3s
nmcli
sleep 3s

echo -e "\n"
read -n1 -p "---------------Please execute Script on Server Master---------------"
echo -e "\n"

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo  -e "---------------Install bind---------------\n"
sleep 5s

echo "[root@Project-08-Task-05 ~]# yum install -y bind"
sleep 3s
yum install -y bind
sleep 3s

#view information
echo "[root@Project-08-Task-05 ~]# systemctl start named"
sleep 3s
systemctl start named
sleep 3s

echo "[root@Project-08-Task-05 ~]# systemctl status named | head -10"
sleep 3s
systemctl status named | head -10
sleep 3s

#set the boot
echo "[root@Project-08-Task-05 ~]# systemctl enable named.service"
sleep 3s
systemctl enable named.service
sleep 3s

#view the status of the run
echo "[root@Project-08-Task-05 ~]# systemctl list-unit-files | grep named.service"
sleep 3s
systemctl list-unit-files | grep named.service
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo  -e "---------------Reload bind---------------\n"
sleep 5s

#reload named
echo "[root@Project-08-Task-05 ~]# systemctl reload named"
sleep 3s
systemctl reload named
sleep 3s

#stop firewalld
echo "[root@Project-08-Task-05 ~]# systemctl stop firewalld"
sleep 3s
systemctl stop firewalld
sleep 3s

echo "[root@Project-08-Task-05 ~]# setenforce 0"
sleep 3s
setenforce 0
sleep 3s

echo -e "\n"
read -n1 -p "---------------Please execute Script on Server Master---------------"
echo -e "\n"

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo -e "---------------Configure primary and secondary synchronization and view---------------\n"
sleep 5s

#configure primary and secondary synchronization and view on DNS slave
echo "[root@Project-08-Task-05 ~]# cp -f /etc/named.conf /etc/named.conf.bak1"
sleep 3s
cp -f /etc/named.conf /etc/named.conf.bak1
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i '/zone \".\" IN {/,+3d' /etc/named.conf"
sleep 3s
sed -i '/zone "." IN {/,+3d' /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i '/named.rfc1912.zones/d' /etc/named.conf"
sleep 3s
sed -i '/named.rfc1912.zones/d' /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i 's/127.0.0.1/10.10.2.122/g' /etc/named.conf"
sleep 3s
sed -i 's/127.0.0.1/10.10.2.122/g' /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i 's/localhost/any/g' /etc/named.conf"
sleep 3s
sed -i 's/localhost/any/g' /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i \"/allow-query/a allow-transfer { none; };\nmasterfile-format text;\" /etc/named.conf"
sleep 3s
sed -i "/allow-query/a allow-transfer { none; };\nmasterfile-format text;" /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# cat >> /etc/named.conf <<EOF"
sleep 3s
echo "> key \"area-key\" {"
sleep 3s
echo ">         algorithm hmac-md5;"
sleep 3s
echo ">         secret \"areaSecret\";"
sleep 3s
echo "> };"
sleep 3s
echo "> key \"common-key\" {"
sleep 3s
echo ">         algorithm hmac-md5;"
sleep 3s
echo ">         secret \"commonSecret\";"
sleep 3s
echo "> };"
sleep 3s
echo "> EOF"
sleep 3s
cat >> /etc/named.conf <<EOF

key "area-key" {
        algorithm hmac-md5;
        secret "areaSecret";
};

key "common-key" {
        algorithm hmac-md5;
        secret "commonSecret";
};

EOF

read -p "Please enter the secret value in the area-key generated by the DNS Master host: " areaSecret
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i 's#areaSecret#'''$areaSecret'''#g' /etc/named.conf"
sleep 3s
sed -i 's#areaSecret#'''$areaSecret'''#g' /etc/named.conf
sleep 3s

read -p "Please enter the secret value in the common-key generated by the DNS Master host: " commonSecret
sleep 3s

echo "[root@Project-08-Task-05 ~]# sed -i 's#commonSecret#'''$commonSecret'''#g' /etc/named.conf"
sleep 3s
sed -i 's#commonSecret#'''$commonSecret'''#g' /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo -e "---------------Configure specific zones---------------\n"
sleep 5s

echo "[root@Project-08-Task-05 ~]# cat >> /etc/named.conf <<EOF"
sleep 3s
echo "> view \"area\" {"
sleep 3s
echo "> 	match-clients{key area-key; 10.10.2.0/26;};"
sleep 3s
echo "> 	zone \".\" IN {"
sleep 3s
echo "> 		type hint;"
sleep 3s
echo "> 		file \"named.ca\";"
sleep 3s
echo "> 	};"
sleep 3s
echo "> 	zone \"domain.com\" IN {"
sleep 3s
echo "> 		type slave;"
sleep 3s
echo "> 		file \"com-domain-area\";"
sleep 3s
echo "> 		masters{10.10.2.120;};"
sleep 3s
echo "> 	};"
sleep 3s
echo "> 	zone \"3.10.10.in-addr.arpa\" IN {"
sleep 3s
echo "> 		type slave;"
sleep 3s
echo "> 		file \"10.10.3.area\";"
sleep 3s
echo "> 		masters{10.10.2.120;};"
sleep 3s
echo "> 	};"
sleep 3s
echo "> };"
sleep 3s
echo "> view \"common\" {"
sleep 3s
echo "> 	match-clients { key common-key; any;};"
sleep 3s
echo "> 	server 10.10.2.120 { keys common-key; };"
sleep 3s
echo "> 	zone \".\" IN {"
sleep 3s
echo "> 		type hint;"
sleep 3s
echo "> 		file \"named.ca\";"
sleep 3s
echo "> 	};"
sleep 3s
echo "> 	zone \"domain.com\" IN {"
sleep 3s
echo "> 		type slave;"
sleep 3s
echo "> 		file \"com-domain-common\";"
sleep 3s
echo "> 		masters{10.10.2.120;};"
sleep 3s
echo "> 	};"
sleep 3s
echo "> 	zone \"4.10.10.in-addr.arpa\" IN {"
sleep 3s
echo "> 		type slave;"
sleep 3s
echo "> 		file \"10.10.4.common\";"
sleep 3s
echo "> 		masters{10.10.2.120;};"
sleep 3s
echo "> 	};"
sleep 3s
echo "> };"
sleep 3s
echo "> EOF"
sleep 3s

cat >> /etc/named.conf <<EOF

view "area" {
	match-clients{key area-key; 10.10.2.0/26;};
	server 10.10.2.120 { keys area-key; };
	zone "." IN {
		type hint;
		file "named.ca";
	};
	zone "domain.com" IN {
		type slave;
		file "com-domain-area";
		masters{10.10.2.120;};
	};
	zone "3.10.10.in-addr.arpa" IN {
		type slave;
		file "10.10.3.area";
		masters{10.10.2.120;};
	};
};

view "common" {
	match-clients { key common-key; any;};
	server 10.10.2.120 { keys common-key; };
	zone "." IN {
		type hint;
		file "named.ca";
	};
	zone "domain.com" IN {
		type slave;
		file "com-domain-common";
		masters{10.10.2.120;};
	};
	zone "4.10.10.in-addr.arpa" IN {
		type slave;
		file "10.10.4.common";
		masters{10.10.2.120;};
	};
};

EOF

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo -e "---------------Check the correctness of bind master configuration file---------------\n"
sleep 5s

#check the correctness of bind master configuration file
echo "[root@Project-08-Task-05 ~]# named-checkconf /etc/named.conf"
sleep 3s
named-checkconf /etc/named.conf
sleep 3s

echo "[root@Project-08-Task-05 ~]# systemctl reload named"
sleep 3s
systemctl reload named
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# ls /var/named"
sleep 3s
ls /var/named
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# cat /var/named/com-domain-area"
sleep 3s
cat /var/named/com-domain-area
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# cat /var/named/com-domain-common"
sleep 3s
cat /var/named/com-domain-common
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]#cat /var/named/10.10.3.area "
sleep 3s
cat /var/named/10.10.3.area
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# cat /var/named/10.10.4.common"
sleep 3s
cat /var/named/10.10.4.common
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# cat /var/named/data/named.run | head -n 60"
sleep 3s
cat /var/named/data/named.run | head -n 60
sleep 3s

echo -e "\n"
read -n1 -p "---------------Please execute Script on Server Master---------------"
echo -e "\n"

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo -e "---------------Testing domain name resolution service on DNS slave---------------\n"
sleep 5s

echo "[root@Project-08-Task-05 ~]# yum install -y bind-utils"
sleep 3s
yum install -y bind-utils
sleep 3s

echo "[root@Project-08-Task-05 ~]# clear"
sleep 3s
clear

echo "[root@Project-08-Task-05 ~]# dig www.domain.com @10.10.2.120"
sleep 3s
dig www.domain.com @10.10.2.120
sleep 3s

echo "[root@Project-08-Task-05 ~]# dig www.domain.com @10.10.2.122"
sleep 3s
dig www.domain.com @10.10.2.122
sleep 3s

echo -e "\n"
read -n1 -p "---------------Please execute Script on Server Master---------------"
echo -e "\n"

#***************reader shell end*****************